#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : syslog-ng
Version  : 3.16.1
Release  : 3
URL      : https://github.com/balabit/syslog-ng/releases/download/syslog-ng-3.16.1/syslog-ng-3.16.1.tar.gz
Source0  : https://github.com/balabit/syslog-ng/releases/download/syslog-ng-3.16.1/syslog-ng-3.16.1.tar.gz
Summary  : Next-generation syslog server
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0+ LGPL-2.1
Requires: syslog-ng-bin
Requires: syslog-ng-lib
Requires: syslog-ng-data
Requires: rabbitmq-c
BuildRequires : bison
BuildRequires : flex
BuildRequires : libcap-dev
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(json-c)
BuildRequires : pkgconfig(libpcre)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pkgconfig(openssl)
BuildRequires : pkgconfig(python)
BuildRequires : pkgconfig(python2)
BuildRequires : pkgconfig(python3)
BuildRequires : pkgconfig(uuid)
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : rabbitmq-c-dev
BuildRequires : rabbitmq-c-lib
BuildRequires : setuptools
BuildRequires : valgrind

%description
syslog-ng is an enhanced log daemon, supporting a wide range of input and
output methods: syslog, unstructured text, message queues, databases (SQL
and NoSQL alike) and more.

Key features:

 * receive and send RFC3164 and RFC5424 style syslog messages
 * work with any kind of unstructured data
 * receive and send JSON formatted messages
 * classify and structure logs with builtin parsers (csv-parser(),
   db-parser(), ...)
 * normalize, crunch and process logs as they flow through the system
 * hand on messages for further processing using message queues (like
   AMQP), files or databases (like PostgreSQL or MongoDB).

%package bin
Summary: bin components for the syslog-ng package.
Group: Binaries
Requires: syslog-ng-data

%description bin
bin components for the syslog-ng package.


%package data
Summary: data components for the syslog-ng package.
Group: Data

%description data
data components for the syslog-ng package.


%package dev
Summary: dev components for the syslog-ng package.
Group: Development
Requires: syslog-ng-lib
Requires: syslog-ng-bin
Requires: syslog-ng-data
Provides: syslog-ng-devel

%description dev
dev components for the syslog-ng package.


%package lib
Summary: lib components for the syslog-ng package.
Group: Libraries
Requires: syslog-ng-data

%description lib
lib components for the syslog-ng package.


%prep
%setup -q -n syslog-ng-3.16.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1529704162
%configure --disable-static --enable-amqp --disable-redis --disable-http --disable-smtp --disable-python --disable-geoip --disable-geoip2 --disable-libbson --disable-mongodb --disable-stomp --disable-tcp-wrapper --disable-ipv6 --disable-spoof-source --disable-java --with-mongoc=no --disable-debug --disable-gprof --disable-memtrace --disable-dependency-tracking --disable-valgrind --disable-manpages --with-jsonc=system
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1529704162
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/dqtool
/usr/bin/loggen
/usr/bin/pdbtool
/usr/bin/syslog-ng
/usr/bin/syslog-ng-ctl
/usr/bin/syslog-ng-debun
/usr/bin/update-patterndb

%files data
%defattr(-,root,root,-)
/usr/share/syslog-ng/include/scl/apache/apache.conf
/usr/share/syslog-ng/include/scl/cim/adapter.conf
/usr/share/syslog-ng/include/scl/cim/template.conf
/usr/share/syslog-ng/include/scl/cisco/plugin.conf
/usr/share/syslog-ng/include/scl/default-network-drivers/plugin.conf
/usr/share/syslog-ng/include/scl/elasticsearch/plugin.conf
/usr/share/syslog-ng/include/scl/ewmm/ewmm.conf
/usr/share/syslog-ng/include/scl/graphite/README
/usr/share/syslog-ng/include/scl/graphite/plugin.conf
/usr/share/syslog-ng/include/scl/graylog2/plugin.conf
/usr/share/syslog-ng/include/scl/hdfs/plugin.conf
/usr/share/syslog-ng/include/scl/iptables/iptables.conf
/usr/share/syslog-ng/include/scl/kafka/plugin.conf
/usr/share/syslog-ng/include/scl/loadbalancer/gen-loadbalancer.sh
/usr/share/syslog-ng/include/scl/loadbalancer/plugin.conf
/usr/share/syslog-ng/include/scl/loggly/loggly.conf
/usr/share/syslog-ng/include/scl/logmatic/logmatic.conf
/usr/share/syslog-ng/include/scl/mbox/mbox.conf
/usr/share/syslog-ng/include/scl/nodejs/plugin.conf
/usr/share/syslog-ng/include/scl/osquery/plugin.conf
/usr/share/syslog-ng/include/scl/pacct/plugin.conf
/usr/share/syslog-ng/include/scl/rewrite/cc-mask.conf
/usr/share/syslog-ng/include/scl/snmptrap/snmptrapd-source.conf
/usr/share/syslog-ng/include/scl/solaris/plugin.conf
/usr/share/syslog-ng/include/scl/sudo/sudo.conf
/usr/share/syslog-ng/include/scl/syslogconf/README
/usr/share/syslog-ng/include/scl/syslogconf/convert-syslogconf.awk
/usr/share/syslog-ng/include/scl/syslogconf/plugin.conf
/usr/share/syslog-ng/include/scl/system/plugin.conf
/usr/share/syslog-ng/include/scl/telegram/telegram.conf
/usr/share/syslog-ng/include/scl/windowseventlog/plugin.conf
/usr/share/syslog-ng/include/scl/windowseventlog/windowseventlog.xml
/usr/share/syslog-ng/tools/__pycache__/merge-grammar.cpython-36.pyc
/usr/share/syslog-ng/tools/cfg-grammar.y
/usr/share/syslog-ng/tools/lex-rules.am
/usr/share/syslog-ng/tools/merge-grammar.py
/usr/share/syslog-ng/tools/system-expand.sh
/usr/share/syslog-ng/xsd/patterndb-1.xsd
/usr/share/syslog-ng/xsd/patterndb-2.xsd
/usr/share/syslog-ng/xsd/patterndb-3.xsd
/usr/share/syslog-ng/xsd/patterndb-4.xsd
/usr/share/syslog-ng/xsd/patterndb-5.xsd

%files dev
%defattr(-,root,root,-)
/usr/include/syslog-ng/ack_tracker.h
/usr/include/syslog-ng/afinter.h
/usr/include/syslog-ng/alarms.h
/usr/include/syslog-ng/apphook.h
/usr/include/syslog-ng/atomic.h
/usr/include/syslog-ng/block-ref-parser.h
/usr/include/syslog-ng/bookmark.h
/usr/include/syslog-ng/cache.h
/usr/include/syslog-ng/cfg-args.h
/usr/include/syslog-ng/cfg-block-generator.h
/usr/include/syslog-ng/cfg-block.h
/usr/include/syslog-ng/cfg-grammar.h
/usr/include/syslog-ng/cfg-lexer-subst.h
/usr/include/syslog-ng/cfg-lexer.h
/usr/include/syslog-ng/cfg-parser.h
/usr/include/syslog-ng/cfg-tree.h
/usr/include/syslog-ng/cfg.h
/usr/include/syslog-ng/children.h
/usr/include/syslog-ng/compat/compat.h
/usr/include/syslog-ng/compat/getent-bb.h
/usr/include/syslog-ng/compat/getent.h
/usr/include/syslog-ng/compat/getutent.h
/usr/include/syslog-ng/compat/glib.h
/usr/include/syslog-ng/compat/lfs.h
/usr/include/syslog-ng/compat/openssl_support.h
/usr/include/syslog-ng/compat/pcre.h
/usr/include/syslog-ng/compat/pio.h
/usr/include/syslog-ng/compat/socket.h
/usr/include/syslog-ng/compat/string.h
/usr/include/syslog-ng/compat/time.h
/usr/include/syslog-ng/control/control-commands.h
/usr/include/syslog-ng/control/control-main.h
/usr/include/syslog-ng/control/control-server.h
/usr/include/syslog-ng/control/control.h
/usr/include/syslog-ng/crypto.h
/usr/include/syslog-ng/debugger/debugger-main.h
/usr/include/syslog-ng/debugger/debugger.h
/usr/include/syslog-ng/debugger/tracer.h
/usr/include/syslog-ng/dnscache.h
/usr/include/syslog-ng/driver.h
/usr/include/syslog-ng/evtlog.h
/usr/include/syslog-ng/evtmaps.h
/usr/include/syslog-ng/fdhelpers.h
/usr/include/syslog-ng/file-perms.h
/usr/include/syslog-ng/filter/filter-call.h
/usr/include/syslog-ng/filter/filter-cmp.h
/usr/include/syslog-ng/filter/filter-expr-parser.h
/usr/include/syslog-ng/filter/filter-expr.h
/usr/include/syslog-ng/filter/filter-in-list.h
/usr/include/syslog-ng/filter/filter-netmask.h
/usr/include/syslog-ng/filter/filter-netmask6.h
/usr/include/syslog-ng/filter/filter-op.h
/usr/include/syslog-ng/filter/filter-pipe.h
/usr/include/syslog-ng/filter/filter-pri.h
/usr/include/syslog-ng/filter/filter-re.h
/usr/include/syslog-ng/filter/filter-tags.h
/usr/include/syslog-ng/find-crlf.h
/usr/include/syslog-ng/gprocess.h
/usr/include/syslog-ng/gsockaddr.h
/usr/include/syslog-ng/gsocket.h
/usr/include/syslog-ng/host-id.h
/usr/include/syslog-ng/host-resolve.h
/usr/include/syslog-ng/hostname.h
/usr/include/syslog-ng/ivykis/iv.h
/usr/include/syslog-ng/ivykis/iv_avl.h
/usr/include/syslog-ng/ivykis/iv_event.h
/usr/include/syslog-ng/ivykis/iv_event_raw.h
/usr/include/syslog-ng/ivykis/iv_fd_pump.h
/usr/include/syslog-ng/ivykis/iv_inotify.h
/usr/include/syslog-ng/ivykis/iv_list.h
/usr/include/syslog-ng/ivykis/iv_popen.h
/usr/include/syslog-ng/ivykis/iv_signal.h
/usr/include/syslog-ng/ivykis/iv_thread.h
/usr/include/syslog-ng/ivykis/iv_tls.h
/usr/include/syslog-ng/ivykis/iv_wait.h
/usr/include/syslog-ng/ivykis/iv_work.h
/usr/include/syslog-ng/late_ack_tracker.h
/usr/include/syslog-ng/loggen_helper.h
/usr/include/syslog-ng/loggen_plugin.h
/usr/include/syslog-ng/logmatcher.h
/usr/include/syslog-ng/logmpx.h
/usr/include/syslog-ng/logmsg/gsockaddr-serialize.h
/usr/include/syslog-ng/logmsg/logmsg-serialize-fixup.h
/usr/include/syslog-ng/logmsg/logmsg-serialize.h
/usr/include/syslog-ng/logmsg/logmsg.h
/usr/include/syslog-ng/logmsg/nvhandle-descriptors.h
/usr/include/syslog-ng/logmsg/nvtable-serialize-endianutils.h
/usr/include/syslog-ng/logmsg/nvtable-serialize-legacy.h
/usr/include/syslog-ng/logmsg/nvtable-serialize.h
/usr/include/syslog-ng/logmsg/nvtable.h
/usr/include/syslog-ng/logmsg/serialization.h
/usr/include/syslog-ng/logmsg/tags-serialize.h
/usr/include/syslog-ng/logmsg/tags.h
/usr/include/syslog-ng/logmsg/timestamp-serialize.h
/usr/include/syslog-ng/logpipe.h
/usr/include/syslog-ng/logproto/logproto-buffered-server.h
/usr/include/syslog-ng/logproto/logproto-builtins.h
/usr/include/syslog-ng/logproto/logproto-client.h
/usr/include/syslog-ng/logproto/logproto-dgram-server.h
/usr/include/syslog-ng/logproto/logproto-framed-client.h
/usr/include/syslog-ng/logproto/logproto-framed-server.h
/usr/include/syslog-ng/logproto/logproto-indented-multiline-server.h
/usr/include/syslog-ng/logproto/logproto-multiline-server.h
/usr/include/syslog-ng/logproto/logproto-record-server.h
/usr/include/syslog-ng/logproto/logproto-regexp-multiline-server.h
/usr/include/syslog-ng/logproto/logproto-server.h
/usr/include/syslog-ng/logproto/logproto-text-client.h
/usr/include/syslog-ng/logproto/logproto-text-server.h
/usr/include/syslog-ng/logproto/logproto.h
/usr/include/syslog-ng/logqueue-fifo.h
/usr/include/syslog-ng/logqueue.h
/usr/include/syslog-ng/logreader.h
/usr/include/syslog-ng/logsource.h
/usr/include/syslog-ng/logstamp.h
/usr/include/syslog-ng/logthrdestdrv.h
/usr/include/syslog-ng/logwriter.h
/usr/include/syslog-ng/mainloop-call.h
/usr/include/syslog-ng/mainloop-io-worker.h
/usr/include/syslog-ng/mainloop-worker.h
/usr/include/syslog-ng/mainloop.h
/usr/include/syslog-ng/memtrace.h
/usr/include/syslog-ng/messages.h
/usr/include/syslog-ng/misc.h
/usr/include/syslog-ng/ml-batched-timer.h
/usr/include/syslog-ng/module-config.h
/usr/include/syslog-ng/modules/add-contextual-data/add-contextual-data-parser.h
/usr/include/syslog-ng/modules/add-contextual-data/add-contextual-data-selector.h
/usr/include/syslog-ng/modules/add-contextual-data/add-contextual-data-template-selector.h
/usr/include/syslog-ng/modules/add-contextual-data/add-contextual-data.h
/usr/include/syslog-ng/modules/add-contextual-data/context-info-db.h
/usr/include/syslog-ng/modules/add-contextual-data/contextual-data-record-scanner.h
/usr/include/syslog-ng/modules/add-contextual-data/csv-contextual-data-record-scanner.h
/usr/include/syslog-ng/msg-format.h
/usr/include/syslog-ng/nondumpable-allocator.h
/usr/include/syslog-ng/parse-number.h
/usr/include/syslog-ng/parser/parser-expr-parser.h
/usr/include/syslog-ng/parser/parser-expr.h
/usr/include/syslog-ng/pathutils.h
/usr/include/syslog-ng/pe-versioning.h
/usr/include/syslog-ng/persist-state.h
/usr/include/syslog-ng/persistable-state-header.h
/usr/include/syslog-ng/persistable-state-presenter.h
/usr/include/syslog-ng/plugin-types.h
/usr/include/syslog-ng/plugin.h
/usr/include/syslog-ng/poll-events.h
/usr/include/syslog-ng/poll-fd-events.h
/usr/include/syslog-ng/pragma-parser.h
/usr/include/syslog-ng/presented-persistable-state.h
/usr/include/syslog-ng/rcptid.h
/usr/include/syslog-ng/reloc.h
/usr/include/syslog-ng/resolved-configurable-paths.h
/usr/include/syslog-ng/rewrite/rewrite-expr-parser.h
/usr/include/syslog-ng/rewrite/rewrite-expr.h
/usr/include/syslog-ng/rewrite/rewrite-groupset.h
/usr/include/syslog-ng/rewrite/rewrite-set-tag.h
/usr/include/syslog-ng/rewrite/rewrite-set.h
/usr/include/syslog-ng/rewrite/rewrite-subst.h
/usr/include/syslog-ng/rewrite/rewrite-unset.h
/usr/include/syslog-ng/ringbuffer.h
/usr/include/syslog-ng/run-id.h
/usr/include/syslog-ng/scanner/csv-scanner/csv-scanner.h
/usr/include/syslog-ng/scanner/kv-scanner/kv-scanner.h
/usr/include/syslog-ng/scanner/list-scanner/list-scanner.h
/usr/include/syslog-ng/scratch-buffers.h
/usr/include/syslog-ng/secret-storage.h
/usr/include/syslog-ng/seqnum.h
/usr/include/syslog-ng/serialize.h
/usr/include/syslog-ng/service-management.h
/usr/include/syslog-ng/signal-handler.h
/usr/include/syslog-ng/stats/stats-cluster-logpipe.h
/usr/include/syslog-ng/stats/stats-cluster-single.h
/usr/include/syslog-ng/stats/stats-cluster.h
/usr/include/syslog-ng/stats/stats-control.h
/usr/include/syslog-ng/stats/stats-counter.h
/usr/include/syslog-ng/stats/stats-csv.h
/usr/include/syslog-ng/stats/stats-log.h
/usr/include/syslog-ng/stats/stats-query-commands.h
/usr/include/syslog-ng/stats/stats-query.h
/usr/include/syslog-ng/stats/stats-registry.h
/usr/include/syslog-ng/stats/stats-syslog.h
/usr/include/syslog-ng/stats/stats.h
/usr/include/syslog-ng/str-format.h
/usr/include/syslog-ng/str-repr/decode.h
/usr/include/syslog-ng/str-repr/encode.h
/usr/include/syslog-ng/str-utils.h
/usr/include/syslog-ng/string-list.h
/usr/include/syslog-ng/syslog-names.h
/usr/include/syslog-ng/syslog-ng-config.h
/usr/include/syslog-ng/syslog-ng.h
/usr/include/syslog-ng/template/common-template-typedefs.h
/usr/include/syslog-ng/template/compiler.h
/usr/include/syslog-ng/template/escaping.h
/usr/include/syslog-ng/template/function.h
/usr/include/syslog-ng/template/macros.h
/usr/include/syslog-ng/template/repr.h
/usr/include/syslog-ng/template/simple-function.h
/usr/include/syslog-ng/template/templates.h
/usr/include/syslog-ng/template/user-function.h
/usr/include/syslog-ng/thread-utils.h
/usr/include/syslog-ng/timeutils.h
/usr/include/syslog-ng/tls-support.h
/usr/include/syslog-ng/tlscontext.h
/usr/include/syslog-ng/transport/logtransport.h
/usr/include/syslog-ng/transport/multitransport.h
/usr/include/syslog-ng/transport/transport-aux-data.h
/usr/include/syslog-ng/transport/transport-factory-id.h
/usr/include/syslog-ng/transport/transport-factory-registry.h
/usr/include/syslog-ng/transport/transport-factory-socket.h
/usr/include/syslog-ng/transport/transport-factory-tls.h
/usr/include/syslog-ng/transport/transport-factory.h
/usr/include/syslog-ng/transport/transport-file.h
/usr/include/syslog-ng/transport/transport-pipe.h
/usr/include/syslog-ng/transport/transport-socket.h
/usr/include/syslog-ng/transport/transport-tls.h
/usr/include/syslog-ng/type-hinting.h
/usr/include/syslog-ng/userdb.h
/usr/include/syslog-ng/utf8utils.h
/usr/include/syslog-ng/uuid.h
/usr/include/syslog-ng/value-pairs/cmdline.h
/usr/include/syslog-ng/value-pairs/evttag.h
/usr/include/syslog-ng/value-pairs/transforms.h
/usr/include/syslog-ng/value-pairs/value-pairs.h
/usr/include/syslog-ng/versioning.h
/usr/lib64/libevtlog.so
/usr/lib64/libloggen_helper.so
/usr/lib64/libloggen_plugin.so
/usr/lib64/libsecret-storage.so
/usr/lib64/libsyslog-ng.so
/usr/lib64/pkgconfig/syslog-ng-native-connector.pc
/usr/lib64/pkgconfig/syslog-ng.pc

%files lib
%defattr(-,root,root,-)
/usr/lib/syslog-ng/libadd-contextual-data.so
/usr/lib/syslog-ng/libafamqp.so
/usr/lib/syslog-ng/libaffile.so
/usr/lib/syslog-ng/libafprog.so
/usr/lib/syslog-ng/libafsocket.so
/usr/lib/syslog-ng/libafuser.so
/usr/lib/syslog-ng/libappmodel.so
/usr/lib/syslog-ng/libbasicfuncs.so
/usr/lib/syslog-ng/libcef.so
/usr/lib/syslog-ng/libconfgen.so
/usr/lib/syslog-ng/libcryptofuncs.so
/usr/lib/syslog-ng/libcsvparser.so
/usr/lib/syslog-ng/libdate.so
/usr/lib/syslog-ng/libdbparser.so
/usr/lib/syslog-ng/libdisk-buffer.so
/usr/lib/syslog-ng/libgraphite.so
/usr/lib/syslog-ng/libhook-commands.so
/usr/lib/syslog-ng/libjson-plugin.so
/usr/lib/syslog-ng/libkvformat.so
/usr/lib/syslog-ng/liblinux-kmsg-format.so
/usr/lib/syslog-ng/libmap-value-pairs.so
/usr/lib/syslog-ng/libpseudofile.so
/usr/lib/syslog-ng/libsdjournal.so
/usr/lib/syslog-ng/libsnmptrapd-parser.so
/usr/lib/syslog-ng/libstardate.so
/usr/lib/syslog-ng/libsyslogformat.so
/usr/lib/syslog-ng/libsystem-source.so
/usr/lib/syslog-ng/libtags-parser.so
/usr/lib/syslog-ng/libtfgetent.so
/usr/lib/syslog-ng/libxml.so
/usr/lib/syslog-ng/loggen/libloggen_socket_plugin.so
/usr/lib/syslog-ng/loggen/libloggen_ssl_plugin.so
/usr/lib64/libevtlog-3.16.so.0
/usr/lib64/libevtlog-3.16.so.0.0.0
/usr/lib64/libloggen_helper-3.16.so.0
/usr/lib64/libloggen_helper-3.16.so.0.0.0
/usr/lib64/libloggen_plugin-3.16.so.0
/usr/lib64/libloggen_plugin-3.16.so.0.0.0
/usr/lib64/libsecret-storage.so.0
/usr/lib64/libsecret-storage.so.0.0.0
/usr/lib64/libsyslog-ng-3.16.so.0
/usr/lib64/libsyslog-ng-3.16.so.0.0.0
